"""add_is_read_to_stories

Revision ID: 1ac0aa0364d2
Revises: f014d42e3ec2
Create Date: 2026-07-18 19:26:18.545871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ac0aa0364d2'
down_revision = 'f014d42e3ec2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('is_read', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'is_read')
    # ### end Alembic commands ###