"""add_hn_created_at_to_stories

Revision ID: 420ab25b7da1
Revises: 1ac0aa0364d2
Create Date: 2026-07-18 21:29:41.778593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '420ab25b7da1'
down_revision = '1ac0aa0364d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('hn_created_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'hn_created_at')
    # ### end Alembic commands ###