"""add_ai_activity_log

Revision ID: 5039278cb307
Revises: 420ab25b7da1
Create Date: 2026-07-18 22:55:10.877561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5039278cb307'
down_revision = '420ab25b7da1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_activity_logs_event_type'), 'ai_activity_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_ai_activity_logs_id'), 'ai_activity_logs', ['id'], unique=False)
    op.create_index(op.f('ix_ai_activity_logs_story_id'), 'ai_activity_logs', ['story_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_activity_logs_story_id'), table_name='ai_activity_logs')
    op.drop_index(op.f('ix_ai_activity_logs_id'), table_name='ai_activity_logs')
    op.drop_index(op.f('ix_ai_activity_logs_event_type'), table_name='ai_activity_logs')
    op.drop_table('ai_activity_logs')
    # ### end Alembic commands ###