"""add_device_type_to_devices

Revision ID: 74214f548893
Revises: 6a8a8de8c42c
Create Date: 2026-07-30 22:53:15.991382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74214f548893'
down_revision = '6a8a8de8c42c'
branch_labels = None
depends_on = None


def upgrade():
    # Add column as nullable first
    op.add_column('devices', sa.Column('device_type', sa.String(), nullable=True))
    # Backfill existing rows with "android"
    op.execute("UPDATE devices SET device_type = 'android' WHERE device_type IS NULL")
    # Now make it non-nullable
    op.alter_column('devices', 'device_type', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'device_type')
    # ### end Alembic commands ###