"""add_device_type_to_devices

Revision ID: 74214f548893
Revises: 6a8a8de8c42c
Create Date: 2026-07-30 22:53:15.991382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74214f548893'
down_revision = '6a8a8de8c42c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('device_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'device_type')
    # ### end Alembic commands ###