"""add_worker_event_fields_to_ai_activity_log

Revision ID: aa58620f591c
Revises: aaf50844bd97
Create Date: 2026-07-24 18:50:59.314777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa58620f591c'
down_revision = 'aaf50844bd97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_activity_logs', sa.Column('event_category', sa.String(length=16), nullable=True))
    op.add_column('ai_activity_logs', sa.Column('worker_event_type', sa.String(length=32), nullable=True))
    op.add_column('ai_activity_logs', sa.Column('worker_status', sa.String(length=16), nullable=True))
    op.add_column('ai_activity_logs', sa.Column('worker_phase', sa.String(length=16), nullable=True))
    op.add_column('ai_activity_logs', sa.Column('error_code', sa.String(length=64), nullable=True))
    op.add_column('ai_activity_logs', sa.Column('error_summary', sa.String(length=512), nullable=True))
    op.create_index(op.f('ix_ai_activity_logs_event_category'), 'ai_activity_logs', ['event_category'], unique=False)
    op.create_index(op.f('ix_ai_activity_logs_worker_event_type'), 'ai_activity_logs', ['worker_event_type'], unique=False)

    # Backfill: existing records are all AI call logs
    op.execute(
        "UPDATE ai_activity_logs SET event_category = 'ai_call' WHERE event_category IS NULL"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_activity_logs_worker_event_type'), table_name='ai_activity_logs')
    op.drop_index(op.f('ix_ai_activity_logs_event_category'), table_name='ai_activity_logs')
    op.drop_column('ai_activity_logs', 'error_summary')
    op.drop_column('ai_activity_logs', 'error_code')
    op.drop_column('ai_activity_logs', 'worker_phase')
    op.drop_column('ai_activity_logs', 'worker_status')
    op.drop_column('ai_activity_logs', 'worker_event_type')
    op.drop_column('ai_activity_logs', 'event_category')
    # ### end Alembic commands ###