"""add story_title to ai_activity_log

Revision ID: aaf50844bd97
Revises: 5039278cb307
Create Date: 2026-07-19 15:56:54.972424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaf50844bd97'
down_revision = '5039278cb307'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_activity_logs', sa.Column('story_title', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_activity_logs', 'story_title')
    # ### end Alembic commands ###