"""remove unused smtp columns from settings

Revision ID: f014d42e3ec2
Revises: 20260712_add_telegram_settings
Create Date: 2026-07-17 16:43:00.379456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f014d42e3ec2'
down_revision = '20260712_add_telegram_settings'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('settings', 'telegram_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('settings', 'smtp_from')
    op.drop_column('settings', 'smtp_password')
    op.drop_column('settings', 'anthropic_api_key')
    op.drop_column('settings', 'openai_api_key')
    op.drop_column('settings', 'smtp_port')
    op.drop_column('settings', 'smtp_username')
    op.drop_column('settings', 'smtp_host')
    op.alter_column('stories', 'is_translated',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stories', 'is_translated',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.add_column('settings', sa.Column('smtp_host', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('settings', sa.Column('smtp_username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('settings', sa.Column('smtp_port', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('settings', sa.Column('openai_api_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('settings', sa.Column('anthropic_api_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('settings', sa.Column('smtp_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('settings', sa.Column('smtp_from', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('settings', 'telegram_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###